[
  ./deployment/deployment.nix
  ./deployment/file.nix
  ./nix/nix.nix
  ./nix/nixpkgs.nix
  ./variant/variant.nix
  ./variant/nixos.nix
  ./variant/nix-darwin.nix
  ./variant/home-manager.nix
  ./variant/shell.nix
  ./hardware/configuration.nix
  ./hardware/disk.nix
  ./networking/pppoe.nix
  ./networking/bridge.nix
  ./networking/router.nix
  ./networking/clash.nix
  ./users/users.nix
  ./security/keys.nix
  ./security/ssh-key.nix
  ./security/passwd.nix
  ./environment/packages.nix
  ./environment/make.nix
  ./environment/variables.nix
  ./virtualisation/podman.nix
  ./programs/bash.nix
  ./programs/fish.nix
  ./programs/helix.nix
  ./programs/zellij.nix
  ./programs/git.nix
  ./programs/ssh.nix
  ./programs/code-server.nix
  ./system/system.nix
  ./shell/shell.nix
  ./toolchain/gcc.nix
  ./toolchain/clang.nix
  ./toolchain/rust.nix
  ./toolchain/tex.nix
  ./toolchain/golang.nix
  ./development/linux.nix
]
