[
  ./shell/burn
  ./shell/squirrel.nix
  ./shell/linux.nix
  ./shell/bpf.nix
  ./shell/d2l.nix
  ./shell/nvidia-gpu.nix
  ./shell/rdma.nix
  ./shell/mihomo.nix
  ./shell/gcc.nix
  ./shell/llvm.nix
]
